#!/bin/sh
# Description: Script to get battery status

source $HOME/.config/dwmblocks/scripts/sb-status2d

function equivalent_icon() {
    # Determine the proportional character based on input
    characters=("!󰂎" "" "" "" "" "" "" "" "" "" "")
    proportional_index=$(($1 * 9 / 100))

    if [ "$1" -gt 100 ]; then
        echo "${characters[7]}"
        return
    fi

    echo "${characters[$proportional_index]}"
}

for battery in /sys/class/power_supply/BAT?; do
    percent=$(cat "$battery/capacity")  # battery percentage
    status="$(cat "$battery/status")"   # battery status

    if  [ "$percent" -gt 75 ]; then
        color=$s2d_green1
    elif [ "$percent" -gt 45 ]; then
        color=$s2d_fg0
    elif [ "$percent" -gt 20 ]; then
        color=$s2d_yellow1
    else
        color=$s2d_red1
    fi


    [ "$status" = "Charging" ] && icon_charge="󱐥"

    icon_battery=$(equivalent_icon $percent)

    printf "%s%s%s %d%%%s" "$color" "$icon_charge" "$icon_battery" "$percent" "$s2d_reset"
done && exit 0
