#!/bin/sh
#▁ ▂ ▃ ▄ ▅ ▆ ▇ █
#0 1 2 3 4 5 6 7

function map_to_unicode() {
    # Determine the proportional character based on input
    characters=("▁" "▂" "▃" "▄" "▅" "▆" "▇" "█")
    proportional_index=$(($1 * 7 / 100))

    if [ "$1" -gt 100 ]; then
        echo "${characters[7]}"
        return
    fi

    echo "${characters[$proportional_index]}"
}
